import type { SiteContent } from "./types";

export const de: SiteContent = {
  hero: {
    badge: "Offen für neue Aufgaben · Remote / Umzug",
    headline: ["Ich entwerfe, architektiere und", "baue Produkte, die genutzt werden."],
    tagline: "Software-Ingenieur · Product Builder · KI-Entwickler",
    bio: "Ich bin Abdelhay, Software-Ingenieur aus Tanger. Ich verwandle komplexe Ideen in skalierbare digitale Produkte — von intuitiven Oberflächen über robuste Backends bis zu KI-gestützter Automatisierung. Mit 2 Jahren praktischer Erfahrung, aktuell bei Mooroot, nach dem Aufbau von Automatisierungsdiensten in Deutschland.",
    statusLine: "Bereit, produktionsreifen Code auszuliefern. Spezialisiert auf skalierbare Architekturen und pixelgenaue Benutzererlebnisse.",
    ctaPrimary: "Projekte ansehen",
    ctaSecondary: "Kontakt aufnehmen",
  },
  stats: [
    { value: "1.", label: "Regionaler Hackathon-Sieger" },
    { value: "12+", label: "Full-Stack-Projekte umgesetzt" },
    { value: "2+", label: "Jahre praktische Erfahrung" },
  ],
  companies: [
    { name: "pragmatic minds GmbH", role: "Praktikant Software-Entwicklung", period: "2025" },
    { name: "Mooroot", role: "Full-Stack-Entwickler", period: "2025 — heute" },
    { name: "Solicode", role: "Full-Stack- & Mobile-Ausbildung", period: "2024 — 2026" },
    { name: "Freelance", role: "Web- & Produktentwicklung", period: "2023 — heute" },
  ],
  caseStudy: {
    eyebrow: "Ausgewählte Fallstudie",
    title: "AttendanceFlow AMS",
    summary: "Ein EdTech-Anwesenheitsverwaltungssystem, das manuelle administrative Abläufe um schätzungsweise 70 % reduziert und fehleranfällige 'Paper-to-Laptop'-Prozesse durch ein modulares Laravel-Backend und ein empathisches UI ersetzt.",
    sections: [
      { heading: "Problem", body: "TODO — Das eigentliche Problem beschreiben: manuelle, fehleranfällige Anwesenheitserfassung mit ~70 % Zeitverlust." },
      { heading: "Rahmenbedingungen", body: "TODO — Rahmenbedingungen: variable Arbeitsabläufe, geringe technische Vorkenntnisse der Nutzer, begrenzte Infrastruktur." },
      { heading: "Architektur", body: "TODO — Architektur: modulares Laravel-MVC-Backend, React + Vite Frontend, MySQL-Schema, rollenbasierter Zugriff." },
      { heading: "Wichtige Entscheidungen", body: "TODO — Entscheidungen und Kompromisse: warum modulares Backend, warum die gewählten UX-Muster." },
      { heading: "Ergebnis & Wirkung", body: "TODO — Messbares Ergebnis: eingesparte Zeit, Akzeptanz, gelernte Lektionen und geplante Verbesserungen." },
    ],
    metrics: [
      { value: "70%", label: "Zeitersparnis" },
      { value: "MVC", label: "Modulare Architektur" },
      { value: "In Entw.", label: "Aktueller Status" },
    ],
    github: "https://github.com/abdelhaymallouli/AttendanceFlow-AMS",
    image: "/screenshots/AttendanceFlow.webp",
  },
  process: [
    { step: "Verstehen", desc: "Das echte Problem und die Menschen dahinter verstehen." },
    { step: "Entwerfen", desc: "UX und Architektur vor dem Bauen gestalten." },
    { step: "Bauen", desc: "Sauberen, SOLID, testgetriebenen Code iterativ ausliefern." },
    { step: "Liefern", desc: "Deployen, messen und verfeinern, was wirklich zählt." },
  ],
  expertise: [
    {
      category: "Backend",
      items: [
        { name: "Laravel", level: 90, years: "2J" },
        { name: "Go (Golang)", level: 75, years: "1J" },
        { name: "PHP (OOP)", level: 88, years: "2J" },
        { name: "RESTful APIs", level: 90 },
        { name: "PostgreSQL / MySQL", level: 85 },
      ],
    },
    {
      category: "Frontend & Mobile",
      items: [
        { name: "React 19", level: 90, years: "2J" },
        { name: "Next.js", level: 85 },
        { name: "TypeScript", level: 85 },
        { name: "Kotlin + Jetpack Compose", level: 70 },
        { name: "Tailwind CSS", level: 92 },
      ],
    },
    {
      category: "DevOps & Infrastruktur",
      items: [
        { name: "Docker", level: 78 },
        { name: "Linux / Apache", level: 75 },
        { name: "GitFlow", level: 85 },
        { name: "Cloud-Deployment", level: 72 },
      ],
    },
  ],
  experience: [
    {
      role: "Praktikant Software-Entwicklung",
      company: "pragmatic minds GmbH",
      location: "Kirchheim unter Teck, Deutschland (Remote)",
      period: "Juli – August 2025",
      type: "Praktikum",
      description: "Entwicklung produktionsreifer Microservices und HR-Automatisierungstools in einem deutschen Scrum-Team.",
      highlights: [
        "Entwicklung von Moco-bot und AbwesenheitsBot mit Go und Microsoft Graph API (OAuth2)",
        "Containerisierung aller Dienste mit Docker",
        "Tägliche Code-Reviews und technische Abstimmungen auf Deutsch",
        "Integration von Personio- und Outlook-Systemen",
      ],
      tech: ["Go", "Docker", "Microsoft Graph API", "OAuth2", "Mattermost"],
    },
    {
      role: "Mobile & Full-Stack Development (Jahr 2)",
      company: "Solicode",
      location: "Tanger, Marokko",
      period: "2025 – 2026",
      type: "Ausbildung",
      description: "Fortgeschrittene Spezialisierung in Enterprise Web- und Mobile-Entwicklung.",
      highlights: [
        "Native Android-Apps mit Kotlin und Jetpack Compose",
        "Komplexe Laravel-Backends mit RESTful APIs",
        "Docker und Webserver-Administration (Apache, SSL/TLS)",
        "GitFlow und Scrum in Teamprojekten",
      ],
      tech: ["Kotlin", "Jetpack Compose", "Laravel", "Docker", "React", "TypeScript"],
    },
    {
      role: "Full-Stack Web Development (Jahr 1)",
      company: "Solicode",
      location: "Tanger, Marokko",
      period: "2024 – 2025",
      type: "Ausbildung",
      description: "Grundlage in moderner Webentwicklung mit Fokus auf PHP, React und Datenbanken.",
      highlights: [
        "React-Frontends mit TypeScript und Tailwind CSS",
        "PHP (OOP) und Laravel Backends",
        "Datenbankmodellierung (MySQL)",
        "Agile/Scrum und Git/GitHub",
      ],
      tech: ["React", "PHP", "MySQL", "Tailwind CSS", "Figma"],
    },
  ],
  certifications: [
    {
      icon: "🎓",
      title: "Full-Stack & Mobile Development",
      issuer: "Solicode Diplom",
      date: "2024 – 2026",
      desc: "Zweijährige berufsbildende Ausbildung in Full-Stack Web- und Mobile-Entwicklung.",
      file: "/certificates/Solicode_Diplom.pdf",
    },
    {
      icon: "☁️",
      title: "Deploy Scalable React Apps on Cloud",
      issuer: "Udemy Zertifikat",
      date: "Sept. 2024",
      desc: "Praktisches Cloud-Deployment mit Linode, Apache und Docker.",
    },
    {
      icon: "⚛️",
      title: "React Complete Developer Course",
      issuer: "Udemy Zertifikat",
      date: "Aug. 2024",
      desc: "Fortgeschrittene React-Entwicklung mit modernen Patterns.",
    },
  ],
  education: [
    {
      school: "Solicode",
      program: "Full-Stack & Mobile Development",
      period: "2024 – 2026",
      desc: "Intensive berufsbildende Ausbildung in Web, Mobile, DevOps und agilen Methoden.",
    },
  ],
  languages: [
    { name: "Arabisch", level: "Muttersprache", pct: 100 },
    { name: "Englisch", level: "B2 / C1", pct: 85 },
    { name: "Deutsch", level: "B1 (B2-Kurs laufend)", pct: 70 },
    { name: "Französisch", level: "A2", pct: 30 },
  ],
  achievements: [
    { value: "12+", label: "Projekte umgesetzt" },
    { value: "2+", label: "Jahre Erfahrung" },
    { value: "1.", label: "Hackathon-Sieg" },
    { value: "3", label: "Unternehmen" },
  ],
  contact: {
    title: "Lass uns etwas bauen",
    cta: "Kontakt aufnehmen",
    email: "abdelhay.mallouli@gmail.com",
    location: "Tanger, Marokko",
    availability: "Offen für neue Aufgaben · Remote / Umzug",
    timezone: "GMT+1 (WEST)",
    responseTime: "In der Regel innerhalb von 24 Stunden",
  },
  openSource: [],
  testimonials: [],
  blog: [],
  now: [],
  toolbox: [],
};
