import type { SiteContent } from "./types";

export const en: SiteContent = {
  hero: {
    badge: "Open to work · Remote / Relocation",
    headline: ["I design, architect and", "build products people use."],
    tagline: "Software Engineer · Product Builder · AI Developer",
    bio: "I'm Abdelhay, a software engineer based in Tangier. I turn complex ideas into scalable digital products — from intuitive interfaces to robust backends and AI-powered automation. Backed by 2 years of hands-on experience, currently engineering at Mooroot after building automation services in Germany.",
    statusLine: "Ready to deploy production-grade code. Specializing in scalable architectures and pixel-perfect user experiences.",
    ctaPrimary: "View Projects",
    ctaSecondary: "Get in touch",
  },
  stats: [
    { value: "1st", label: "Regional Hackathon Winner" },
    { value: "12+", label: "Full-Stack Projects Shipped" },
    { value: "2+", label: "Years of Hands-on Experience" },
  ],
  companies: [
    { name: "pragmatic minds GmbH", role: "Software Development Intern", period: "2025" },
    { name: "Mooroot", role: "Full-Stack Engineer", period: "2025 — Present" },
    { name: "Solicode", role: "Full-Stack & Mobile Training", period: "2024 — 2026" },
    { name: "Freelance", role: "Web & Product Development", period: "2023 — Present" },
  ],
  caseStudy: {
    eyebrow: "Featured Case Study",
    title: "AttendanceFlow AMS",
    summary: "An EdTech attendance-management system that cut manual administrative workflows by an estimated 70%, replacing brittle paper-to-laptop processes with a modular Laravel backend and an empathetic UI.",
    sections: [
      { heading: "Problem", body: "TODO — Describe the real problem: manual, error-prone attendance tracking causing ~70% time loss and frustration for staff." },
      { heading: "Constraints", body: "TODO — Constraints: variable institutional workflows, low technical literacy of end users, limited infrastructure." },
      { heading: "Architecture", body: "TODO — Architecture: modular Laravel MVC backend, React + Vite front end, MySQL schema, role-based access." },
      { heading: "Key Decisions", body: "TODO — Decisions and trade-offs: why modular backend, why the chosen UX patterns, how workflows were made configurable." },
      { heading: "Outcome & Impact", body: "TODO — Measured outcome: time saved, adoption, lessons learned, and planned improvements." },
    ],
    metrics: [
      { value: "70%", label: "Time saved" },
      { value: "MVC", label: "Modular architecture" },
      { value: "In dev", label: "Current status" },
    ],
    github: "https://github.com/abdelhaymallouli/AttendanceFlow-AMS",
    image: "/screenshots/AttendanceFlow.webp",
  },
  process: [
    { step: "Discover", desc: "Understand the real problem and the people behind it." },
    { step: "Design", desc: "Shape the UX and architecture before building." },
    { step: "Build", desc: "Ship clean, SOLID, test-driven code, iteratively." },
    { step: "Deliver", desc: "Deploy, measure, and refine what actually matters." },
  ],
  expertise: [
    {
      category: "Backend",
      items: [
        { name: "Laravel", level: 90, years: "2y" },
        { name: "Go (Golang)", level: 75, years: "1y" },
        { name: "PHP (OOP)", level: 88, years: "2y" },
        { name: "RESTful APIs", level: 90 },
        { name: "PostgreSQL / MySQL", level: 85 },
      ],
    },
    {
      category: "Frontend & Mobile",
      items: [
        { name: "React 19", level: 90, years: "2y" },
        { name: "Next.js", level: 85 },
        { name: "TypeScript", level: 85 },
        { name: "Kotlin + Jetpack Compose", level: 70 },
        { name: "Tailwind CSS", level: 92 },
      ],
    },
    {
      category: "DevOps & Infrastructure",
      items: [
        { name: "Docker", level: 78 },
        { name: "Linux / Apache", level: 75 },
        { name: "GitFlow", level: 85 },
        { name: "Cloud Deployment", level: 72 },
      ],
    },
  ],
  experience: [
    {
      role: "Software Development Intern",
      company: "pragmatic minds GmbH",
      location: "Kirchheim unter Teck, Germany (Remote)",
      period: "Jul – Aug 2025",
      type: "Internship",
      description: "Developed production-ready microservices and HR automation tools in a German Scrum team.",
      highlights: [
        "Built Moco-bot and AbwesenheitsBot using Go and Microsoft Graph API (OAuth2)",
        "Containerized services with Docker",
        "Daily code reviews and technical discussions in German",
        "Integrated Personio and Outlook systems",
      ],
      tech: ["Go", "Docker", "Microsoft Graph API", "OAuth2", "Mattermost"],
    },
    {
      role: "Mobile & Full-Stack Development (Year 2)",
      company: "Solicode",
      location: "Tangier, Morocco",
      period: "2025 – 2026",
      type: "Training",
      description: "Advanced specialization in enterprise web and mobile development.",
      highlights: [
        "Native Android apps with Kotlin and Jetpack Compose",
        "Complex Laravel backends with RESTful APIs",
        "Docker and web server administration",
        "GitFlow and Scrum in team projects",
      ],
      tech: ["Kotlin", "Jetpack Compose", "Laravel", "Docker", "React", "TypeScript"],
    },
    {
      role: "Full-Stack Web Development (Year 1)",
      company: "Solicode",
      location: "Tangier, Morocco",
      period: "2024 – 2025",
      type: "Training",
      description: "Foundation in modern web development with focus on PHP, React and databases.",
      highlights: [
        "React frontends with TypeScript and Tailwind",
        "PHP (OOP) and Laravel backends",
        "Database modeling (MySQL)",
        "Agile/Scrum and Git/GitHub",
      ],
      tech: ["React", "PHP", "MySQL", "Tailwind CSS", "Figma"],
    },
  ],
  certifications: [
    {
      icon: "🎓",
      title: "Full-Stack & Mobile Development",
      issuer: "Solicode Diploma",
      date: "2024 – 2026",
      desc: "Two-year vocational training in full-stack web and mobile development.",
      file: "/certificates/Solicode_Diplom.pdf",
    },
    {
      icon: "☁️",
      title: "Deploy Scalable React Apps on Cloud",
      issuer: "Udemy Certificate",
      date: "Sep 2024",
      desc: "Hands-on cloud deployment with Linode, Apache and Docker.",
    },
    {
      icon: "⚛️",
      title: "React Complete Developer Course",
      issuer: "Udemy Certificate",
      date: "Aug 2024",
      desc: "Advanced React development with modern patterns.",
    },
  ],
  education: [
    {
      school: "Solicode",
      program: "Full-Stack & Mobile Development",
      period: "2024 – 2026",
      desc: "Intensive vocational bootcamp covering web, mobile, DevOps and agile methods.",
    },
  ],
  languages: [
    { name: "Arabic", level: "Native", pct: 100 },
    { name: "English", level: "B2 / C1", pct: 85 },
    { name: "German", level: "B1 (B2 in progress)", pct: 70 },
    { name: "French", level: "A2", pct: 30 },
  ],
  achievements: [
    { value: "12+", label: "Projects delivered" },
    { value: "2+", label: "Years experience" },
    { value: "1st", label: "Hackathon win" },
    { value: "3", label: "Companies worked with" },
  ],
  contact: {
    title: "Let's build something",
    cta: "Get in touch",
    email: "abdelhay.mallouli@gmail.com",
    location: "Tangier, Morocco",
    availability: "Open to work · Remote / Relocation",
    timezone: "GMT+1 (WEST)",
    responseTime: "Usually within 24 hours",
  },
  // ── Empty-until-supplied (render as "coming soon") ──────────────────────────
  openSource: [],
  testimonials: [],
  blog: [],
  now: [],
  toolbox: [],
};
